config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian], message: '`%value` is not valid' }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: {in: 0..5}
  validates :content, presence: true
  # validates :restaurant_id, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was updated!'
    else
      render :edit
    end
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end


  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit current restaurant</h1>

<%= simple_form_for [@restaurant] do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :category %>
<br>
<%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>See all restaurants</h1>

<ul>
<% @restaurants.each do |restaurant| %>
<li><%= restaurant.name %></li>
<% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>

<%= simple_form_for [@restaurant] do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :category %>
<br>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name%></h1>
<h2>Cuisine: <%= @restaurant.category%></h2>
<p><%= @restaurant.address%></p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn btn-primary" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-primary" %> |
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>

app/views/reviews/new.html.erb
<h1>Create a new review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content %>
<%= f.input :rating, collection: 0..5 %>
<br>
<%= f.submit %>
<% end %>